#!/usr/bin/env python3
"""Usage: loview <FILE> -- view a document in any LibreOffice-openable document in vim using pandoc
for Markup preservation.

Author: Sebastian Humenda
Licence: 2020, LGPL-3

This script uses Libreoffice and Pandoc to convert any format that Libreoffice
converts to Markdown and views it in Vim.

By setting the environment variable $EDITOR, you can select your favourite
editor. Defaults to vim.

ToDo:

-   allow to view the HTML file straight in a (text) browser to preserve tables
"""

import os
import shlex
import subprocess
import sys

def execute(command, communication=True):
    text = ''
    if communication:
        proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        # Libreoffice does not use error codes properly, look for "error"
        text = '\n'.join([t.decode(sys.getdefaultencoding())
            for t in proc.communicate() if t])
    else:
        proc = subprocess.Popen(command)
    ret = proc.wait()
    if 'error' in text or 'Error' in text or ret > 0:
        print(f"Error while executing: {command}")
        if text:
            print('   ', text.replace('\n', '\n    ').rstrip())
        sys.exit(38)
    return text

def get_editor():
    if os.environ.get('EDITOR'):
        return os.environ['EDITOR']
    if not shutil.which('vim'): # Nano is the de-facto standard these days
        return 'nano'
    return 'vim'

if not len(sys.argv) > 1:
    print("Must provide a file as argument")
    sys.exit(42)

document_path = sys.argv[1]
document_dir = os.path.dirname(document_path)
if document_dir:
    # libreoffice has strange --output-dir rules, change cwd
    os.chdir(document_dir)
document_path = os.path.basename(document_path)

basename, extension = os.path.splitext(document_path)
intermediate_html = None
if len(extension) >= 2 and len(extension) < 5:
    intermediate_html = f'{basename}.html'
else:
    intermediate_html = f'{basename}.html'

execute(["libreoffice", "--convert-to", "html", document_path])
text = execute(["pandoc", "-t", "markdown", intermediate_html])
intermediate_text = intermediate_html + '.md'
with open(intermediate_text, 'w') as file:
    file.write(text)
execute([get_editor(), intermediate_text], communication=False)
os.remove(intermediate_html)
