[project]
name = "mdview"
version = "0.1"

[project.scripts]
md_cleanup = "md_cleanup:main"
loview = "loview:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["loview", "md_cleanup"]
